from typing import List

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from src.ingest import DEFAULT_DATA_PATH, ingest
from src.rag import DEFAULT_MODEL, query_rag

app = FastAPI(title="RAG API", description="API for RAG System")


class QueryRequest(BaseModel):
    query: str = Field(min_length=1, description="The user question to answer with retrieved context")
    model: str = Field(default=DEFAULT_MODEL, description="OpenRouter model name")


class Source(BaseModel):
    source: str
    content_preview: str
    score: float


class QueryResponse(BaseModel):
    answer: str
    sources: List[Source]


@app.post("/query", response_model=QueryResponse)
async def query_endpoint(request: QueryRequest):
    full_response = ""
    sources = []

    try:
        for chunk, docs in query_rag(request.query, model_name=request.model, stream=False):
            full_response += chunk
            if docs:
                sources = docs
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    formatted_sources = [
        Source(
            source=doc.metadata.get("source", "Unknown"),
            content_preview=doc.page_content[:200],
            score=float(score),
        )
        for doc, score in sources
    ]

    if not full_response:
        raise HTTPException(status_code=500, detail="No response generated by query pipeline")

    return QueryResponse(answer=full_response, sources=formatted_sources)


@app.post("/ingest")
async def ingest_endpoint(clear_existing: bool = False):
    try:
        ingest(DEFAULT_DATA_PATH, clear_existing=clear_existing)
        return {
            "status": "success",
            "message": "Ingestion complete",
            "cleared_existing": clear_existing,
        }
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
